version: "3.9"

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - ./:/app/
    environment:
      MYSQL_DATABASE: product
      MYSQL_USER: customer
      MYSQL_PASSWORD: customer
      MYSQL_ROOT_PASSWORD: customer
    networks:
      - internal

  app:
    command: java -jar target/demo-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - database
    volumes:
      - ./:/app/app
    links:
      - database
    networks:
      - internal
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/product?useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=customer
      - SPRING_DATASOURCE_PASSWORD=customer
      - spring_rabbitmq_host=rabbitmq-container
      - spring_rabbitmq_port=5672

networks:
  internal:
    name: internal